services:
  neko-site:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5

networks:
  backend:
    name: backend
    driver: bridge
    external: true
